#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time
import sys
import os

def clear_screen():
    """Limpiar la pantalla"""
    os.system('clear' if os.name != 'nt' else 'cls')

def print_slow(text, delay=0.05):
    """Imprimir texto lentamente"""
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    print()

def pausa(segundos=2):
    """Pausa dramática"""
    time.sleep(segundos)

# ============================================================================
# PARTE 1: DÍAS DE GLORIA
# ============================================================================

def texto_dias_de_gloria_1():
    """Introducción a los días de gloria"""
    clear_screen()
    print_slow("\n\n")
    print_slow("═══════════════════════════════════════════════════════════════", 0.02)
    print_slow("                    CAPÍTULO 2: LA CAÍDA DEL CREADOR", 0.03)
    print_slow("═══════════════════════════════════════════════════════════════", 0.02)
    print_slow("\n\n")
    pausa(2)
    
    print_slow("Han pasado varios años desde que recibiste el poder divino...", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("El reino que construiste es próspero y hermoso.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Los humanos te adoran como a un dios.", 0.04)
    pausa(2)

def texto_dias_de_gloria_2():
    """Descripción del reino próspero"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Tu reino es magnífico:", 0.04)
    pausa(1)
    print_slow("\n")
    print_slow("• Palacios de mármol blanco brillan bajo el sol", 0.04)
    pausa(0.8)
    print_slow("• Jardines llenos de flores y árboles frutales", 0.04)
    pausa(0.8)
    print_slow("• Fuentes de agua cristalina en cada plaza", 0.04)
    pausa(0.8)
    print_slow("• Campos de cultivo que producen abundante comida", 0.04)
    pausa(2)

def texto_dias_de_gloria_3():
    """La adoración del pueblo"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Cada mañana, el pueblo se reúne en la plaza central...", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Te traen ofrendas:", 0.04)
    pausa(1)
    print_slow("\n")
    print_slow("• Flores frescas", 0.04)
    pausa(0.5)
    print_slow("• Frutas de la cosecha", 0.04)
    pausa(0.5)
    print_slow("• Artesanías hechas con amor", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Cantan himnos en tu honor.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Te llaman 'El Creador', 'El Salvador', 'El Elegido'.", 0.04)
    pausa(2)

def texto_dias_de_gloria_4():
    """Los pretendientes"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Tu fama ha crecido tanto que...", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Muchas personas quieren estar cerca de ti.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Hay dos personas que destacan entre todos:", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("KAEL - Un joven ambicioso de ojos oscuros.", 0.04)
    pausa(1)
    print_slow("         Siempre te halaga y busca tu aprobación.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("LYRA - Una mujer carismática de sonrisa encantadora.", 0.04)
    pausa(1)
    print_slow("        Te trae regalos y te dedica poemas.", 0.04)
    pausa(2)

def texto_dias_de_gloria_5():
    """La vida perfecta"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Tu vida es perfecta.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Eres amado, respetado, adorado.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Cada día creas algo nuevo:", 0.04)
    pausa(1)
    print_slow("\n")
    print_slow("• Nuevas plantas para alimentar al pueblo", 0.04)
    pausa(0.8)
    print_slow("• Animales hermosos que alegran los campos", 0.04)
    pausa(0.8)
    print_slow("• Edificios majestuosos que tocan el cielo", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Te sientes invencible.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Te sientes... como un dios.", 0.04)
    pausa(3)

# ============================================================================
# PARTE 2: EL REGRESO DEL ÁNGEL
# ============================================================================

def texto_regreso_angel_1():
    """El día que todo cambió"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Pero un día...", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Todo cambió.", 0.04)
    pausa(3)

def texto_regreso_angel_2():
    """La aparición del ángel"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Estás en la plaza central, rodeado de tu pueblo...", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("De repente, el cielo se ilumina.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Una luz cegadora desciende desde las nubes.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("El pueblo grita de asombro y miedo.", 0.04)
    pausa(2)

def texto_regreso_angel_3():
    """El ángel habla"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El ángel de alas blancas aparece frente a ti.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Su voz resuena en toda la plaza:", 0.04)
    pausa(1.5)
    print_slow("\n\n")
    print_slow("'Has cumplido tu propósito.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'El reino está construido.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Ya no necesitas el poder divino.'", 0.05)
    pausa(3)

def texto_regreso_angel_4():
    """La pérdida de poderes"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Antes de que puedas responder...", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("El ángel extiende su mano hacia ti.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Sientes una fuerza invisible arrancando algo de tu interior.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Es como si te arrancaran el alma.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Gritas de dolor.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Caes de rodillas.", 0.04)
    pausa(3)

def texto_regreso_angel_5():
    """El poder se va"""
    clear_screen()
    print_slow("\n\n")
    print_slow("La energía divina abandona tu cuerpo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Ya no sientes el poder.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Ya no puedes crear vida.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Ya no eres especial.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Eres... solo un humano.", 0.04)
    pausa(3)

def texto_regreso_angel_6():
    """El ángel se va"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El ángel te mira con indiferencia:", 0.04)
    pausa(1.5)
    print_slow("\n\n")
    print_slow("'Tu trabajo está hecho.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Ahora eres como los demás.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Adiós.'", 0.05)
    pausa(3)
    print_slow("\n\n")
    print_slow("Y desaparece en un destello de luz.", 0.04)
    pausa(3)

# ============================================================================
# PARTE 3: LA CAÍDA
# ============================================================================

def texto_caida_1():
    """El silencio del pueblo"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Te quedas ahí, de rodillas, temblando.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("El pueblo te mira en silencio.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Nadie se acerca a ayudarte.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Nadie dice nada.", 0.04)
    pausa(3)

def texto_caida_2():
    """El rechazo comienza"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Intentas ponerte de pie.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Extiendes tu mano hacia el pueblo:", 0.04)
    pausa(1.5)
    print_slow("\n\n")
    print_slow("'Por favor... ayúdenme...'", 0.05)
    pausa(2)
    print_slow("\n\n")
    print_slow("Pero la gente retrocede.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Te miran con... ¿desprecio?", 0.04)
    pausa(3)

def texto_caida_3():
    """Las primeras palabras crueles"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Alguien entre la multitud grita:", 0.04)
    pausa(1.5)
    print_slow("\n\n")
    print_slow("'¡Ya no eres nuestro dios!'", 0.05)
    pausa(2)
    print_slow("\n\n")
    print_slow("Otro grita:", 0.04)
    pausa(1)
    print_slow("\n\n")
    print_slow("'¡Eres solo un humano común!'", 0.05)
    pausa(2)
    print_slow("\n\n")
    print_slow("Y otro más:", 0.04)
    pausa(1)
    print_slow("\n\n")
    print_slow("'¡No te necesitamos!'", 0.05)
    pausa(3)

def texto_caida_4():
    """El odio crece"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El odio se propaga como fuego.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("La gente que antes te adoraba...", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Ahora te mira con desprecio.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Las ofrendas que te traían...", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Ahora las arrojan al suelo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Los himnos que cantaban en tu honor...", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Ahora son insultos.", 0.04)
    pausa(3)

# ============================================================================
# PARTE 4: LA TRAICIÓN
# ============================================================================

def texto_traicion_1():
    """Kael y Lyra se acercan"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Entre la multitud, ves a Kael y Lyra.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Ellos... los que siempre estuvieron a tu lado.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Seguramente te ayudarán.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("¿Verdad?", 0.04)
    pausa(3)

def texto_traicion_2():
    """La verdad de Kael"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Kael se acerca con una sonrisa fría.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Ya no es la sonrisa amable de antes.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Es una sonrisa cruel.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'¿Sabes algo?'", 0.05)
    pausa(1.5)
    print_slow("\n")
    print_slow("'Nunca te admiré.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Solo quería tu poder.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Y ahora que no lo tienes...'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'No eres nada para mí.'", 0.05)
    pausa(3)

def texto_traicion_3():
    """La verdad de Lyra"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Lyra se ríe.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Es una risa amarga y burlona.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'¿De verdad creíste que te amaba?'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Solo quería estar cerca del poder.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Eres patético.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Siempre lo fuiste.'", 0.05)
    pausa(3)

def texto_traicion_4():
    """El dolor de la traición"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Sus palabras duelen más que perder el poder.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Te sientes vacío.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Traicionado.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Abandonado.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Todo lo que construiste...", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Todo lo que hiciste por ellos...", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("No significó nada.", 0.04)
    pausa(3)

def texto_traicion_5():
    """La conspiración"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Kael y Lyra se miran entre sí.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Lyra habla en voz alta para que todos escuchen:", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'¡Este impostor nos engañó!'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'¡Nunca fue un dios!'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'¡Solo era un humano con suerte!'", 0.05)
    pausa(3)
    print_slow("\n\n")
    print_slow("Kael continúa:", 0.04)
    pausa(1.5)
    print_slow("\n\n")
    print_slow("'¡Debemos expulsarlo del reino!'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'¡No merece estar aquí!'", 0.05)
    pausa(3)

def texto_traicion_6():
    """El pueblo se une contra ti"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El pueblo aplaude.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Gritan de acuerdo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("'¡Fuera!'", 0.05)
    pausa(1)
    print_slow("\n")
    print_slow("'¡Fuera!'", 0.05)
    pausa(1)
    print_slow("\n")
    print_slow("'¡FUERA!'", 0.05)
    pausa(3)

# ============================================================================
# PARTE 5: EL EXILIO
# ============================================================================

def texto_exilio_1():
    """La expulsión"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Te arrastran fuera del reino.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Te empujan.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Te escupen.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Te insultan.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Nadie te defiende.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Nadie te ayuda.", 0.04)
    pausa(3)

def texto_exilio_2():
    """Las puertas se cierran"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Te arrojan más allá de las puertas del reino.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Caes al suelo, cubierto de polvo y lágrimas.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Escuchas el sonido de las puertas cerrándose.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("CLANG.", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("Ese sonido marca el fin de tu vida anterior.", 0.04)
    pausa(3)

def texto_exilio_3():
    """La soledad"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Te quedas ahí, solo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Mirando las puertas cerradas.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("El reino que construiste.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("El pueblo que salvaste.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Todo te ha dado la espalda.", 0.04)
    pausa(3)

def texto_exilio_4():
    """El llanto"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Lloras.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Lloras como nunca antes lo habías hecho.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Lloras por la traición.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Lloras por la pérdida.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Lloras por la soledad.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Lloras hasta que no te quedan más lágrimas.", 0.04)
    pausa(3)

# ============================================================================
# PARTE 6: LA DESESPERACIÓN
# ============================================================================

def texto_desesperacion_1():
    """Los días pasan"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Pasan los días.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Vagas por tierras desoladas.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Sin rumbo.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Sin propósito.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Sin esperanza.", 0.04)
    pausa(3)

def texto_desesperacion_2():
    """Los intentos fallidos"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Intentas usar tus poderes.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Extiendes tus manos hacia el suelo.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Intentas crear vida.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Pero no pasa nada.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("El poder se ha ido.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Para siempre.", 0.04)
    pausa(3)

def texto_desesperacion_3():
    """La rabia"""
    clear_screen()
    print_slow("\n\n")
    print_slow("La tristeza se convierte en rabia.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Gritas al cielo:", 0.04)
    pausa(1.5)
    print_slow("\n\n")
    print_slow("'¡¿POR QUÉ?!'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'¡¿POR QUÉ ME HICISTE ESTO?!'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'¡LO DI TODO POR ELLOS!'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'¡Y ASÍ ME PAGAN!'", 0.05)
    pausa(3)
    print_slow("\n\n")
    print_slow("Pero el cielo no responde.", 0.04)
    pausa(3)

def texto_desesperacion_4():
    """La desesperación total"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Te dejas caer al suelo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Ya no tienes fuerzas.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Ya no tienes esperanza.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Piensas en rendirte.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Piensas en... dejarlo todo.", 0.04)
    pausa(3)

# ============================================================================
# PARTE 7: LA REVELACIÓN
# ============================================================================

def texto_revelacion_1():
    """Una presencia oscura"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Pero entonces...", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Sientes una presencia.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("No es como la del ángel de luz.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Esta presencia es... diferente.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Oscura.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Pero no malvada.", 0.04)
    pausa(3)

def texto_revelacion_2():
    """El ángel caído aparece"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Levantas la mirada.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Frente a ti hay un ser alado.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Pero sus alas no son blancas.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Son negras como la noche.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Es un ángel caído.", 0.04)
    pausa(3)

def texto_revelacion_3():
    """El ángel caído habla"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El ángel caído te mira con compasión.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Su voz es suave pero firme:", 0.04)
    pausa(1.5)
    print_slow("\n\n")
    print_slow("'Sé lo que sientes.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Yo también fui traicionado.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Yo también perdí todo.'", 0.05)
    pausa(3)

def texto_revelacion_4():
    """La verdad sobre Dios"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El ángel caído se sienta a tu lado.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Continúa hablando:", 0.04)
    pausa(1.5)
    print_slow("\n\n")
    print_slow("'¿Quieres saber la verdad?'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Dios no te quitó los poderes porque cumpliste tu propósito.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Te los quitó porque tenía miedo.'", 0.05)
    pausa(3)

def texto_revelacion_5():
    """El miedo de Dios"""
    clear_screen()
    print_slow("\n\n")
    print_slow("'¿Miedo?'", 0.05)
    pausa(1.5)
    print_slow("\n")
    print_slow("Preguntas con voz débil.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("El ángel caído asiente:", 0.04)
    pausa(1.5)
    print_slow("\n\n")
    print_slow("'Sí. Miedo de que te volvieras más poderoso que Él.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Miedo de que el pueblo te adorara más a ti que a Él.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Miedo de perder el control.'", 0.05)
    pausa(3)

def texto_revelacion_6():
    """La culpa no es tuya"""
    clear_screen()
    print_slow("\n\n")
    print_slow("'Nada de esto es tu culpa.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("Dice el ángel caído.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'Fuiste usado.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Como una herramienta.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Y cuando ya no eras útil...'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Te desecharon.'", 0.05)
    pausa(3)

def texto_revelacion_7():
    """La rabia justificada"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Sientes la rabia crecer dentro de ti.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Pero ahora es diferente.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("No es rabia ciega.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Es rabia justificada.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Rabia contra la injusticia.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Rabia contra la traición.", 0.04)
    pausa(3)

def texto_revelacion_8():
    """La pregunta importante"""
    clear_screen()
    print_slow("\n\n")
    print_slow("'¿Qué puedo hacer?'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("Preguntas al ángel caído.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'Ya no tengo poderes.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Soy solo un humano.'", 0.05)
    pausa(3)

def texto_revelacion_9():
    """La respuesta del ángel caído"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El ángel caído sonríe.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Es una sonrisa misteriosa.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'¿Quién dijo que necesitas los poderes divinos?'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Hay otros tipos de poder.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Poderes que Dios no puede quitarte.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Porque no vienen de Él.'", 0.05)
    pausa(3)

def texto_revelacion_10():
    """La esperanza renace"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Por primera vez en días...", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Sientes una chispa de esperanza.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("'¿Qué tipo de poder?'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("Preguntas con urgencia.", 0.04)
    pausa(3)

# ============================================================================
# PARTE 8: EL DESCUBRIMIENTO
# ============================================================================

def texto_descubrimiento_1():
    """El ángel caído enseña"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El ángel caído se levanta.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Señala el suelo bajo tus pies:", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'Mira a tu alrededor.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'¿Qué ves?'", 0.05)
    pausa(3)

def texto_descubrimiento_2():
    """Observando el mundo"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Miras a tu alrededor.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Ves tierra.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Ves el viento moviendo el polvo.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Ves pequeños charcos de agua.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'Veo... elementos.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("Respondes.", 0.04)
    pausa(3)

def texto_descubrimiento_3():
    """La lección comienza"""
    clear_screen()
    print_slow("\n\n")
    print_slow("'Exacto.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("Dice el ángel caído.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'Dios creó el universo con estos elementos.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Pero no son suyos.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Existen por sí mismos.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Y cualquiera puede aprender a usarlos.'", 0.05)
    pausa(3)

def texto_descubrimiento_4():
    """La reflexión"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Piensas en las palabras del ángel caído.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Cuando tenías los poderes divinos...", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Creabas vida de la nada.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Era fácil.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Instantáneo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Pero nunca entendiste cómo funcionaba.", 0.04)
    pausa(3)

def texto_descubrimiento_5():
    """El primer intento"""
    clear_screen()
    print_slow("\n\n")
    print_slow("'Enséñame.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("Le dices al ángel caído.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("Él asiente y señala el suelo:", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'Toca la tierra.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Siente su textura.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Entiende su esencia.'", 0.05)
    pausa(3)

def texto_descubrimiento_6():
    """Conectando con la tierra"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Pones tus manos en el suelo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Al principio no sientes nada especial.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Solo tierra fría y seca.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Pero luego...", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Empiezas a sentir algo más.", 0.04)
    pausa(3)

def texto_descubrimiento_7():
    """La primera conexión"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Es como si la tierra te hablara.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("No con palabras.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Sino con sensaciones.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Sientes su peso.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Su densidad.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Su... voluntad de ser moldeada.", 0.04)
    pausa(3)

def texto_descubrimiento_8():
    """El primer garabato"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Cierras los ojos.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Te concentras.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Mueves tus dedos en la tierra.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Dibujas formas.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Círculos.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Líneas.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Símbolos que no sabías que conocías.", 0.04)
    pausa(3)

def texto_descubrimiento_9():
    """El primer círculo mágico"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Cuando abres los ojos...", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Ves que has dibujado un círculo perfecto.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Con símbolos extraños alrededor.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("El ángel caído sonríe:", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'Acabas de crear tu primer círculo mágico.'", 0.05)
    pausa(3)

def texto_descubrimiento_10():
    """¿Qué es la magia?"""
    clear_screen()
    print_slow("\n\n")
    print_slow("'¿Magia?'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("Preguntas confundido.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("El ángel caído explica:", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'La magia es el arte de manipular los elementos.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'No es poder divino.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Es conocimiento.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Es comprensión.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Es conexión con el mundo.'", 0.05)
    pausa(3)

def texto_descubrimiento_11():
    """Experimentando con tierra"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Pasas horas practicando.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Aprendes a sentir la tierra.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("A moverla con tu mente.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("A darle forma.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("No es como antes.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Es más lento.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Requiere esfuerzo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Pero es TUYO.", 0.04)
    pausa(3)

def texto_descubrimiento_12():
    """El primer logro"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Después de mucho intentar...", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Logras levantar una pequeña piedra del suelo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Flota en el aire frente a ti.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Temblando.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Inestable.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Pero ahí está.", 0.04)
    pausa(3)

def texto_descubrimiento_13():
    """La emoción del descubrimiento"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Sientes una emoción que no habías sentido en días.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("No es el poder divino.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Es algo mejor.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Es el orgullo de haber aprendido algo por ti mismo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Es el orgullo de haber logrado algo con tu propio esfuerzo.", 0.04)
    pausa(3)

def texto_descubrimiento_14():
    """Descubriendo el viento"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El ángel caído te enseña más.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Te enseña a sentir el viento.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("A entender sus corrientes.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("A guiarlo con tu voluntad.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Es más difícil que la tierra.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("El viento es libre.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("No quiere ser controlado.", 0.04)
    pausa(3)

def texto_descubrimiento_15():
    """Dominando el viento"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Pero con paciencia...", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Aprendes a pedirle al viento.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("No a ordenarle.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("A pedirle.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Y el viento responde.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Una brisa suave rodea tu cuerpo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Obedeciendo tu voluntad.", 0.04)
    pausa(3)

def texto_descubrimiento_16():
    """Descubriendo el agua"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Finalmente, el ángel caído te lleva a un pequeño arroyo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("'El agua es el elemento más difícil.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("Dice.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'Porque el agua es vida.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Y la vida tiene su propia voluntad.'", 0.05)
    pausa(3)

def texto_descubrimiento_17():
    """Conectando con el agua"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Metes tus manos en el agua fría.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Sientes su fluir.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Su movimiento constante.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Su adaptabilidad.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("El agua no lucha.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Se adapta.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Fluye alrededor de los obstáculos.", 0.04)
    pausa(3)

def texto_descubrimiento_18():
    """La lección del agua"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Pasas días aprendiendo del agua.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Y el agua te enseña más que magia.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Te enseña a ser flexible.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("A adaptarte.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("A no luchar contra lo inevitable.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Sino a fluir con ello.", 0.04)
    pausa(3)

def texto_descubrimiento_19():
    """Los tres elementos dominados"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Después de semanas de práctica...", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Dominas los tres elementos básicos:", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("• TIERRA - Sólida, confiable, fuerte", 0.04)
    pausa(1)
    print_slow("• VIENTO - Libre, rápido, impredecible", 0.04)
    pausa(1)
    print_slow("• AGUA - Flexible, adaptable, vital", 0.04)
    pausa(3)

def texto_descubrimiento_20():
    """El nuevo propósito"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Ya no eres el mismo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Ya no dependes del poder divino.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Ahora tienes tu propio poder.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Un poder que nadie puede quitarte.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Porque viene de tu conocimiento.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("De tu esfuerzo.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("De tu conexión con el mundo.", 0.04)
    pausa(3)

def texto_descubrimiento_21():
    """La despedida del ángel caído"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El ángel caído se prepara para partir.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("'Mi trabajo aquí está hecho.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("Dice con una sonrisa.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'Ahora el camino es tuyo.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'¿Qué harás con este nuevo poder?'", 0.05)
    pausa(3)

def texto_descubrimiento_22():
    """La decisión"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Piensas en todo lo que has pasado.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("La traición.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("El exilio.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("El dolor.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Pero también piensas en lo que has aprendido.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("La magia.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("La conexión con los elementos.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Tu nuevo poder.", 0.04)
    pausa(3)

def texto_descubrimiento_23():
    """El nuevo comienzo"""
    clear_screen()
    print_slow("\n\n")
    print_slow("Miras al ángel caído y dices:", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'Voy a crear un nuevo mundo.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Un mundo mejor que el anterior.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Un mundo donde nadie sea traicionado.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Un mundo donde todos tengan la oportunidad de aprender.'", 0.05)
    pausa(3)

def texto_descubrimiento_24():
    """Las últimas palabras del ángel caído"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El ángel caído asiente con aprobación.", 0.04)
    pausa(2)
    print_slow("\n\n")
    print_slow("'Ese es un propósito noble.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Pero recuerda...'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'El poder no te hace bueno o malo.'", 0.05)
    pausa(2)
    print_slow("\n")
    print_slow("'Son tus acciones las que te definen.'", 0.05)
    pausa(3)

def texto_descubrimiento_25():
    """El final del capítulo"""
    clear_screen()
    print_slow("\n\n")
    print_slow("El ángel caído desaparece en las sombras.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Te quedas solo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Pero ya no te sientes solo.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Tienes un propósito.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Tienes poder.", 0.04)
    pausa(1.5)
    print_slow("\n")
    print_slow("Y tienes conocimiento.", 0.04)
    pausa(3)
    print_slow("\n\n")
    print_slow("Miras hacia el horizonte.", 0.04)
    pausa(2)
    print_slow("\n")
    print_slow("Tu aventura apenas comienza...", 0.04)
    pausa(3)
    print_slow("\n\n")
    print_slow("═══════════════════════════════════════════════════════════════", 0.02)
    print_slow("                    FIN DEL CAPÍTULO 2", 0.03)
    print_slow("═══════════════════════════════════════════════════════════════", 0.02)
    pausa(3)

